Set up repo as root on Enterprise Linux
On Fedora 29, setting up the repo as a non-root user produces this error:

```
## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.xiLusGCjk8'
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
Error executing command, exiting
```

Including `sudo -E` to set repo as root fixes this problem. I've updated the instructions to include `sudo -E`. I've also added the command to actually install node. (Other distros include this step, so it seemed like it would be good to be consistent.)

FYI, I have tested these steps with Fedora 29 / Node.js 10.14.1. I have not tested with other versions of Node, Fedora, or enterprise Linux.

Thank you for maintaining this fantastic resource!